services:
  tg-bot:
    build: .
    container_name: tg_bot
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_db:/app/data
    ports:
      - "8002:8002"

  ngrok:
    container_name: tg_bot_ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml

volumes:
  sqlite_db: