version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      WEB_SERVER_HOST: 127.0.0.1
      WEB_SERVER_PORT: 8000
      SERVER_WEBHOOK_URL: http://127.0.0.1:8000/webhook
      TELEGRAM_BOT_TOKEN: your-telegram-bot-token
      MONGODB_URI: mongodb://root:example@mongo:27017/chat_db?authSource=admin
      WEBHOOK_URL: http://messege-hub.com/message_service
      WEBHOOK_USER_REGISTRATION_PATH: /register
      WEBHOOK_SEND_MESSAGE_PATH: /send_message
      WEBHOOK_PLATFORM_REGISTRATION_PATH: /register_platform
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: chat_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
