from environs import Env

env = Env()
env.read_env()

BOT_TOKEN = env.str("BOT_TOKEN")

SERVER_HOST = env.str("SERVER_HOST")
SERVER_PORT = env.int("SERVER_PORT")

WEBHOOK_HOST = env.str("WEBHOOK_HOST")
WEBHOOK_PATH = f"/{BOT_TOKEN}"
WEBHOOK_URI = WEBHOOK_HOST + WEBHOOK_PATH

DATABASE_URI = env.str("DATABASE_URI")

MESSAGE_SERVICE_URL = env.str("MESSAGE_SERVICE_URL")
MESSAGE_SERVICE_SEND_MESSAGE_PATH = env.str("MESSAGE_SERVICE_SEND_MESSAGE_PATH")
MESSAGE_SERVICE_USER_REGISTRATION_PATH = env.str(
    "MESSAGE_SERVICE_USER_REGISTRATION_PATH"
)
MESSAGE_SERVICE_PLATFORM_REGISTRATION_PATH = env.str(
    "MESSAGE_SERVICE_PLATFORM_REGISTRATION_PATH"
)


MESSAGE_SERVICE_USER_REGISTRATION_URL = (
    MESSAGE_SERVICE_URL + MESSAGE_SERVICE_USER_REGISTRATION_PATH
)
MESSAGE_SERVICE_SEND_MESSAGE_URL = (
    MESSAGE_SERVICE_URL + MESSAGE_SERVICE_SEND_MESSAGE_PATH
)
MESSAGE_SERVICE_PLATFORM_REGISTRATION_URL = (
    MESSAGE_SERVICE_URL + MESSAGE_SERVICE_PLATFORM_REGISTRATION_PATH
)
